# frozen_string_literal: true

# The `Line::Message::RSpec` module provides integration with RSpec for testing
# applications that generate LINE messages using the `line-message-builder` gem.
# It offers a set of custom matchers to simplify the process of verifying the
# structure and content of generated messages.
#
# To use these matchers, you typically need to require `line/message/rspec` in your
# `spec_helper.rb` or individual spec files:
#
# ```ruby
# # spec/spec_helper.rb
# require 'line/message/rspec'
#
# RSpec.configure do |config|
#   # Include the matchers globally if desired
#   config.include Line::Message::RSpec::Matchers
# end
# ```
#
# Or, include them on a per-file basis:
# ```ruby
# # spec/my_message_generator_spec.rb
# require 'line/message/rspec'
#
# RSpec.describe MyMessageGenerator do
#   include Line::Message::RSpec::Matchers
#
#   # ... your tests ...
# end
# ```
#
# This module primarily acts as a namespace and a loading point for the actual
# matcher implementations.
#
# @see Line::Message::RSpec::Matchers
module Line
  module Message
    module RSpec
      # The `Matchers` module contains all the custom RSpec matchers provided by
      # the `line-message-builder` gem for testing LINE message structures.
      #
      # These matchers are designed to be used with RSpec's `expect` syntax to
      # assert characteristics of message arrays generated by your application.
      #
      # Key Matchers:
      # - {Matchers#have_line_text_message}: Checks for text messages.
      # - {Matchers#have_line_quick_reply}: Checks for messages with specific quick replies.
      # - {Matchers#have_line_flex_message}: Checks for Flex Messages, optionally matching altText.
      # - {Matchers#have_line_flex_bubble}: Checks for Flex Messages containing specific Bubbles.
      # - {Matchers#have_line_flex_component}: A generic matcher for finding components within Flex Messages.
      # - {Matchers#have_line_flex_box}: Checks for Flex Box components.
      # - {Matchers#have_line_flex_text}: Checks for Flex Text components.
      # - {Matchers#have_line_flex_button}: Checks for Flex Button components.
      # - {Matchers#have_line_flex_image}: Checks for Flex Image components.
      #
      # Including this module in your RSpec configuration or specs makes these helper
      # methods (like `have_line_text_message`) available directly.
      module Matchers
        # @!visibility private
        # Utility methods for matchers, e.g., for stringifying hash keys.
        require_relative "matchers/utils"

        # Matcher for text messages.
        # @see HaveTextMessage
        require_relative "matchers/have_text_message"

        # Matcher for quick reply actions.
        # @see HaveQuickReply
        require_relative "matchers/have_quick_reply"

        # Matcher for Flex Messages (primarily checking altText).
        # @see HaveFlexMessage
        require_relative "matchers/have_flex_message"

        # Matcher for Flex Message Bubbles.
        # @see HaveFlexBubble
        require_relative "matchers/have_flex_bubble"

        # Matcher for generic and specific Flex Message components.
        # @see HaveFlexComponent
        require_relative "matchers/have_flex_component"
      end
    end
  end
end
