on:
  workflow_dispatch:
    inputs:
      push:
        description: 'Push to RubyGems'
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      push:
        description: 'Push to RubyGems'
        required: false
        default: true
        type: boolean

  release:
    types:
      - released

env:
  MINIMUM_RUBY_VERSION: '3.1'
  RUBYGEMS_VERSION: '3.5.9'

permissions:
  contents: write
  pull-requests: write
  id-token: write

name: Release

jobs:
  release:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.MINIMUM_RUBY_VERSION }}
          bundler-cache: true
      - name: Build gem
        run: bundle exec rake build
      - name: Upload plain gem
        uses: actions/upload-artifact@v4
        with:
          name: gem
          path: pkg/*.gem
      - name: Configure trusted publishing credentials
        uses: rubygems/configure-rubygems-credentials@v1.0.0
      - name: Publish plain gem
        if: github.event_name == 'release' || inputs.push
        run: gem push pkg/*.gem

